# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Fuji"
license = "Apache-2.0"
licenselink = "https://github.com/amzrk2/hugo-theme-fuji/blob/master/LICENSE"
description = "A minimal Hugo theme with nice theme color."
homepage = "https://github.com/amzrk2/hugo-theme-fuji/"
tags = ["blog", "minimal", "responsive", "dark mode"]
features = ["blog", "minimal", "responsive", "dark mode"]
min_version = "0.62.1"

[author]
  name = "DSRKafuU(amzrk2)"
  homepage = "https://blog.amzrk2.cc/"
