#!/bin/sh
#
# hugo-oldnew-mashup test framework
#
#    Copyright (C) 2019 Daniel F. Dickinson <cshored@thecshore.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

OTS=SUCCESS

PATH="$PATH:./node_modules/.bin"
export PATH


for thscript in "$(pwd)"/tests/scripts/th[0-9][0-9]*.sh; do
	if ! $thscript; then
		OTS=FAIL
		cd ..
		break
	fi
done

if [ "$OTS" != "FAIL" ]; then
	for tscript in "$(pwd)"/tests/scripts/t[0-9][0-9]*.sh; do
		if [ -d ./exampleSite ]; then
			cd ./exampleSite
			if ! $tscript; then
				OTS=FAIL
				cd ..
				break
			fi
			cd ..
		else
			if ! $tscript; then
				OTS=FAIL
				break
			fi
		fi
	done
fi

if [ "$OTS" = "FAIL" ]; then
	echo "FAIL: Build failed"
	exit 3
else
	echo "PASS: Build succeeded"
fi

exit 0
