baseURL = "https://hugo-com-todos-os-temas.netlify.app"
languageCode = "pt-br"
title = "Meu primeiro site Hugo"
#
#
# Como eu baixei todos os temas, é só descomentar o tema que você quer escolher abaixo:
#
# theme = "aafu"
# theme = "Academia-hugo"
# theme = "academic"
# theme = "ace-documentation"
# theme = "aerial"
# theme = "aether"
# theme = "air"
# theme = "airspace-hugo"
# theme = "allegiant"
# theme = "alpha-church"
# theme = "amperage"
# theme = "anatole"
# theme = "anybodyhome"
# theme = "arabica"
# theme = "archie"
# theme = "autophugo"
# theme = "avicenna"
# theme = "axiom"
# theme = "bare-hugo-theme"
# theme = "base16"
# theme = "beautifulhugo"
# theme = "BeyondNothing"
# theme = "bilberry-hugo-theme"
# theme = "Binario"
# theme = "black-and-light"
# theme = "blackburn"
# theme = "blank"
# theme = "Blogpaper"
# theme = "bodhi"
# theme = "bootie-docs"
 theme = "bootstrap-bp-hugo-startpage"
# theme = "bootstrap-bp-hugo-theme"
# theme = "capsule"
# theme = "castanet"
# theme = "cayman-hugo-theme"
# theme = "charaka-hugo-theme"
# theme = "classless-hugo"
# theme = "colordrop"
# theme = "compose"
# theme = "contrast-hugo"
# theme = "crab"
# theme = "cupper-hugo-theme"
# theme = "darksimplicity"
# theme = "detox"
# theme = "devfest-theme-hugo" #===>  Deu erro (tem que configurar melhor).
# theme = "devise"
# theme = "docsy"
# theme = "docter"
# theme = "docuapi"
# theme = "dot-hugo-documentation-theme"
# theme = "edidor"
# theme = "educenter-hugo"
# theme = "elephants"
# theme = "engimo"
# theme = "er"
# theme = "erblog"
# theme = "etch"
# theme = "ezhil"
# theme = "flexible-seo-hugo"
# theme = "forty"
# theme = "foundation-theme"
# theme = "future-imperfect"
# theme = "ghazal"
# theme = "ghostwriter"
# theme = "github-style"
# theme = "gochowdown"
# theme = "gohugo-theme-ananke"
# theme = "grid-side"
# theme = "hallo-hugo"
# theme = "harbor"
# theme = "Hargo-hugo-ecommerce-theme"
# theme = "hermit"
# theme = "hestia-pure"
# theme = "highlights"
# theme = "hpstr-hugo-theme"
# theme = "huginn"
# theme = "hugo.386"
# theme = "hugo-alageek-theme"
# theme = "hugo-apps-theme"
# theme = "hugo-assembly"
# theme = "hugo-bare-min-theme"
# theme = "hugo-bingo"
# theme = "hugo-blog-jeffprod"
# theme = "hugo-book"
# theme = "hugo-bootstrap4"
# theme = "hugo-business-frontpage-theme"
# theme = "hugo-cards"
# theme = "hugo-casper3"
# theme = "hugo-changelog-theme"
# theme = "hugo-classic"
# theme = "hugo-coder"
# theme = "hugo-coder-portfolio"
# theme = "hugo-conference"
# theme = "hugo-creative-portfolio-theme"
# theme = "hugo-devresume-theme"
# theme = "hugo-dusk"
# theme = "hugo-dusky-neon-potato"
# theme = "hugo_eiio"
# theme = "hugo-elate-theme"
# theme = "hugo-eureka"
# theme = "hugo-fabric"
# theme = "hugo-faq-theme"
# theme = "hugo-flex"
# theme = "hugo-frais"
# theme = "hugo-frances-theme"
# theme = "hugo-fresh"
# theme = "hugo-future-imperfect-slim"
# theme = "hugo-goa"
# theme = "hugo-grapes"
# theme = "hugograyscale"
# theme = "hugo-h5bp"
# theme = "hugo-hello-programmer-theme"
# theme = "hugo-hero-theme"
# theme = "hugo-html5up-alpha"
# theme = "hugo-icarus"
# theme = "hugo-icon"
# theme = "hugo-identity-theme"
# theme = "hugo-initio"
# theme = "hugo-ink"
# theme = "hugo-journal"
# theme = "hugo-kiera"
# theme = "hugo-lamp"
# theme = "hugo-lime"
# theme = "hugo-lithium-theme"
# theme = "hugo-lodi-theme"
# theme = "hugo-material-blog"
# theme = "hugo-minimalist-spa"
# theme = "hugo-myportfolio-theme"
# theme = "hugo-nederburg-theme"
# theme = "hugonews"
# theme = "hugo-notepadium"
# theme = "hugo-now"
# theme = "hugo-now-ui"
# theme = "hugo-octopress"
# theme = "hugo-orbit-theme"
# theme = "hugo-pacman-theme"
# theme = "hugo-paper"
# theme = "hugo-piercer-theme"
# theme = "hugo-primer"
# theme = "hugo-refresh"
# theme = "hugo-resume"
# theme = "hugo-rocinante"
# theme = "hugo-serif-theme"
# theme = "hugo-shopping-product-catalogue-simple"
# theme = "hugo-sodium-theme"
# theme = "hugo-spectre-pixel-theme"
# theme = "hugo-split-theme"
# theme = "hugo-starter"
# theme = "hugo-startpage-theme"
# theme = "hugo-stellar-theme"
# theme = "hugo-sugoi"
# theme = "hugo-sustain"
# theme = "hugo-swift-theme"
# theme = "hugo-tailwind-journal"
# theme = "hugo-terrassa-theme"
# theme = "HugoTeX"
# theme = "hugo_theme_adam_eve"
# theme = "hugo-theme-anubis"
# theme = "hugo-theme-basic"
# theme = "hugo-theme-bootstrap4-blog"
# theme = "hugo-theme-cactus-plus"
# theme = "hugo-theme-chunky-poster"
# theme = "hugo-theme-cleanwhite"
# theme = "hugo-theme-codex"
# theme = "hugo-theme-cole"
# theme = "hugo-theme-color-your-world"
# theme = "hugo-theme-console"
# theme = "hugo-theme-den"
# theme = "hugo-theme-diary"
# theme = "hugo-theme-dimension"
# theme = "hugo-theme-doors"
# theme = "hugo-theme-dopetrope"
# theme = "hugo-theme-dream"
# theme = "hugo-theme-easybook"
# theme = "hugo-theme-even"
# theme = "hugo-theme-fuji"
# theme = "hugo-theme-hamburg"
# theme = "hugo-theme-hello-friend"
# theme = "hugo-theme-hello-friend-ng"
# theme = "hugo-theme-introduction"
# theme = "hugo-theme-iris"
# theme = "hugo-theme-jane"
# theme = "hugo-theme-lean-launch-page"
# theme = "hugo-theme-learn"
# theme = "hugo-theme-m10c"
# theme = "hugo-theme-massively"
# theme = "hugo-theme-meme"
# theme = "hugo-theme-minos"
# theme = "hugo-theme-mixedpaper"
# theme = "hugo-theme-nix"
# theme = "hugo-theme-noteworthy"
# theme = "hugo-theme-notrack"
# theme = "hugo-theme-novela"
# theme = "hugo-theme-okayish-blog"
# theme = "hugo_theme_pickles"
# theme = "hugo-theme-prav"
# theme = "hugo-theme-pure"
# theme = "hugo-theme-revealjs"
# theme = "hugo-theme-robotico"
# theme = "hugo-theme-sam"
# theme = "hugo-theme-simple-blog"
# theme = "hugo-theme-sky"
# theme = "hugo-theme-techdoc"
# theme = "hugo-theme-techlog-simple"
# theme = "hugo-theme-terminal"
# theme = "hugo-theme-tokiwa"
# theme = "hugo-theme-tony"
# theme = "hugo-theme-vec"
# theme = "hugo-theme-w3css-basic"
# theme = "hugo-theme-wave"
# theme = "hugo-theme-winning"
# theme = "hugo-theme-yinyang"
# theme = "hugo-theme-yuki"
# theme = "hugo-theme-zdoc"
# theme = "hugo-theme-zen"
# theme = "hugo-theme-zozo"
# theme = "hugo-theme-zzo"
# theme = "hugo-tikva"
# theme = "hugo-tranquilpeak-theme"
# theme = "hugo-travelify-theme"
# theme = "hugo-uilite"
# theme = "hugo-universal-theme"
# theme = "hugo-vitae"
# theme = "hugo-w3-simple"
# theme = "hugo-webslides"
# theme = "hugo-whisper-theme"
# theme = "hugo-xmag"
# theme = "hugo-xmin"
# theme = "hugrid"
# theme = "hyde"
# theme = "hyde-hyde"
# theme = "indigo"
# theme = "infinity-hugo"
# theme = "Influencer-hugo"
# theme = "inkblotty"
# theme = "internet-weblog"
# theme = "KeepIt"
# theme = "khata"
# theme = "kiss"
# theme = "kiss-em"
# theme = "kitab"
# theme = "kraiklyn"
# theme = "kross-hugo-portfolio-template"
# theme = "kube"
# theme = "lanyon"
# theme = "LeaveIt"
# theme = "lekh"
# theme = "light-hugo"
# theme = "liquorice"
# theme = "liva-hugo"
# theme = "LoveIt"
# theme = "mainroad"
# theme = "manis-hugo-theme"
# theme = "material-design"
# theme = "materialize-bp-hugo-theme"
# theme = "mediumish-gohugo-theme"
# theme = "meghna-hugo"
# theme = "mero"
# theme = "Midnight"
# theme = "minimage"
# theme = "minimal"
# theme = "minimal-bootstrap-hugo-theme"
# theme = "minimo"
# theme = "min_night"
# theme = "monopriv"
# theme = "navigator-hugo"
# theme = "new-oldnew-mashup"
# theme = "newsroom"
# theme = "Niello"
# theme = "nofancy"
# theme = "northendlab-hugo"
# theme = "npq-hugo"
# theme = "OneDly-Theme"
# theme = "onepress"
# theme = "onetwothree"
# theme = "origin-hugo-theme"
# theme = "osprey-delight"
# theme = "papaya"
# theme = "paperback"
# theme = "papercss-hugo-theme"
# theme = "paperesque"
# theme = "parsa-hugo-personal-blog-theme"
# theme = "persian-hugo"
# theme = "personal-web"
# theme = "photo-grid"
# theme = "pixyll"
# theme = "polymer"
# theme = "potato-dark"
# theme = "prologue"
# theme = "pulp"
# theme = "purehugo"
# theme = "raditian-free-hugo-theme"
# theme = "ramium"
# theme = "redgood"
# theme = "restaurant-hugo"
# theme = "resto-hugo"
# theme = "reveal-hugo"
# theme = "ronu-hugo-theme"
# theme = "roxo-hugo"
# theme = "sada"
# theme = "script"
# theme = "showcase-hugo-theme"
# theme = "silhouette-hugo"
# theme = "simple-a"
# theme = "simpleit-hugo-theme"
# theme = "simple-style"
# theme = "simplicity"
# theme = "slate"
# theme = "slick"
# theme = "slim"
# theme = "smol"
# theme = "soho"
# theme = "solar-theme-hugo"
# theme = "someparts-hugo"
# theme = "somrat"
# theme = "stip-hugo"
# theme = "story"
# theme = "strange-case"
# theme = "syna"
# theme = "tale-hugo"
# theme = "temas.txt"
# theme = "temp"
# theme = "ticky_tacky_dark"
# theme = "timer-hugo"
# theme = "toha"
# theme = "twentyfourteen"
# theme = "twentynineteen-hugo"
# theme = "twenty-twenty-hugo"
# theme = "vanilla-bootstrap-hugo-theme"
# theme = "vex-hugo"
# theme = "vienna"
# theme = "vncnt-hugo"
# theme = "yourfolio
