---
os: linux
language: go
before_install:
   - sudo apt update
install:
    - sudo apt -y install tidy
script: "FROM_YAML=yes ./ci/travis-cmd.sh"
dist: bionic
branches:
    only:
        - master
        - testing
        - /^devel-[0-9.]+$/
        - /^\d+\.\d+\.\d+$/
        - /^\d+\.\d+\-[a-zA-Z0-9_-]+$/
go:
  - 1.13
